enableTelemetry: false

enableGlobalCache: false

enableHardenedMode: true

packageExtensions:
  "@inquirer/core@^10.0.0":
    dependencies:
      "@types/node": "*"
  "@typescript-eslint/type-utils@8.6.0":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@8.6.0":
    dependencies:
      typescript: "*"

pnpMode: strict

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
