enableTelemetry: false

packageExtensions:
  "@inquirer/core@^10.0.0":
    dependencies:
      "@types/node": "*"
  "@typescript-eslint/type-utils@8.6.0":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@8.6.0":
    dependencies:
      typescript: "*"

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.9.2.cjs

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?