enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

packageExtensions:
  "@inquirer/core@^10.0.0":
    dependencies:
      "@types/node": "*"
  openapi-typescript-codegen@^0.30.0:
    dependencies:
      "@types/json-schema": "*"

pnpMode: strict
