enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

packageExtensions:
  openapi-typescript-codegen@^0.31.0:
    dependencies:
      "@types/json-schema": "^7"
  "@next/eslint-plugin-next@^16.3.1":
    dependencies:
      "eslint": "^9"

pnpMode: strict
